
- name: Allow selinux to listen tomcat ports
  seport:
    ports: "{{ item }}"
    proto: tcp
    setype: http_port_t
    state: present
  with_items: 
    - "{{ tomcat_port }}"
    - "{{ tomcat_shutdown_port }}"
    - "{{ tomcat_ajp_port }}"
    - "{{ tomcat_redirect_port }}"
